

```{r}
library(tidyverse)
library(paletteer)
library(patchwork)
```




# Simulation 1: type 2 error rate comparison
```{r}
dat = read_csv("experiment02.csv")

binomial_interval = function(n,p,which){
  result <- binom.test(as.integer(n*p), n, conf.level = 0.95)
  conf_interval <- result$conf.int
  if(which == "upper"){
    return(conf_interval[[2]])
  }
  else{
    return(conf_interval[[1]])
  }
}


dat %>%
  filter(max_r_hat < 1.1, max_r_hat > 0.9) %>%
  mutate(
    beta_v_x2_sig = ifelse(beta_v_x2_cil*beta_v_x2_cih>0,1,0),
    beta_v_x2_2step_sig = ifelse(beta_v_x2_2step_cil*beta_v_x2_2step_cih>0,1,0)
  ) %>%
  filter(n_each != 30) %>%
  group_by(n_each) %>%
  summarise(
    n = n(),
    mean_time = mean(time_taken),
    x2_2step = mean(beta_v_x2_2step_sig),
    x2 = mean(beta_v_x2_sig)
  ) %>%
  pivot_longer(cols = c(x2_2step,x2),names_to = "method", values_to = "type_2_error_rate") %>%
  mutate(
    cil = map2_dbl(n, type_2_error_rate, ~binomial_interval(.x, .y, "lower")),
    cih = map2_dbl(n, type_2_error_rate, ~binomial_interval(.x, .y, "upper"))
  ) %>%
  ggplot() +
  geom_line(aes(x = n_each, y = type_2_error_rate, color = method)) +
    geom_errorbar(aes(x = n_each, y = type_2_error_rate, ymin = cil, ymax = cih,color = method)) +
  geom_hline(yintercept=  0.05, color = "red")+
  annotate("text", x = 440, y = 0.07, label = "a=0.05", color = "red") +
  scale_color_paletteer_d("fishualize::Acanthurus_coeruleus", labels = c("RegDDM", "2 step")) +
  xlab("number of trials per subject") + 
  ylab("type-2 error rate") 
  
```


# Simulation2: performance under different setup
### computation time for each setup
```{r}
dat = read_csv("simulation2.csv") %>%
  filter(max_r_hat < 1.1, max_r_hat > 0.9) %>%
  filter(N >20 | n_each >20) %>%
  filter(beta_v_0_sd<3)

dat %>%
  group_by(N, n_each) %>%
  summarise(
    n = n(),
    time = mean(time_taken)
  ) %>%
  mutate(N = factor(N)) %>%
  ggplot() +
  geom_line(aes(x = n_each, y = time, color = N)) +
  xlab("number of trials per subject") + 
  ylab("computation time (s)") +
  guides(color=guide_legend(title="Number of Subjects"))
```

### posterior standard deviation
```{r}
draw_figure = function(n_xvars, param){
  fig = dat %>%
    filter(n_xvar == n_xvars) %>%
    group_by(N, n_each) %>%
    summarise(
      mean_param_se = mean(get(paste0(param, "_sd")))
    ) %>%
  mutate(N = factor(N)) %>%
  ggplot() +
  geom_line(aes(x = n_each, y = mean_param_se, color = N)) +
  xlab("") + 
  ylab("") +
  guides(color=guide_legend(title="Number of Subjects")) +
  theme(legend.position = "none") +
  ggtitle(param)
    
  return(fig)
}
fig11 = draw_figure(0, "beta_v_0") + theme(legend.position = "right")
fig21 = draw_figure(1, "beta_v_0")+ ylab("average posterior sd")
fig31 = draw_figure(2, "beta_v_0")
fig22 = draw_figure(1, "beta_v_x1")
fig32 = draw_figure(2, "beta_v_x1") + xlab("number of trials for each subject")
fig33 = draw_figure(2, "beta_v_x2")

fig_all = (fig11+plot_spacer()+plot_spacer())/
  (fig21+fig22+plot_spacer())/
  (fig31+fig32+fig33)

fig_all



```


```{r}
dat = read_csv("simulation3.csv", na = c("", "NA", "NaN", "-Inf")) %>%
  na.omit() %>%
  filter(max_r_hat < 1.1, max_r_hat > 0.9) 

fig1 = dat %>%
  group_by(n_each, cont_level) %>%
  summarise(
    n = n(),
    mse_v = mean(mse_v_0),
    sd_beta_v_0 = mean(beta_v_0_sd)
  ) %>%
  mutate(cont_level = factor(cont_level)) %>%
  ggplot() +
  geom_line(aes(x = n_each, y = mse_v, color = cont_level)) +
  xlab("number of trials per subject") + 
  ylab("posterior standard deviation") +
  ggtitle("v_0") +
  theme(legend.position = "none") 
  

fig2 = dat %>%
  group_by(n_each, cont_level) %>%
  summarise(
    n = n(),
    mse_v = mean(mse_v_0),
    sd_beta_v_0 = mean(beta_v_0_sd)
  ) %>%
  mutate(cont_level = factor(cont_level)) %>%
  ggplot() +
  geom_line(aes(x = n_each, y = sd_beta_v_0, color = cont_level)) +
  xlab("number of trials per subject") + 
  ylab("posterior standard deviation") +
  ggtitle("beta_v_0") + 
  guides(color=guide_legend(title="contaminant level"))

fig1 +fig2

```




# application of RegDDM using real data
```{r}
library(RegDDM)

data1 = read_csv("../test_data/CR_BL.csv")
data1 = data1 %>%
  janitor::clean_names() %>%
  filter(subid>3999, age<40) %>%
  select(subid, age, education, amnart_iq) %>%
  unique() %>%
  na.omit() %>%
  arrange(subid) %>%
  rename(id=subid)


load("../test_data/CR_LetterSterberg_BehaviorData_2024_05_21.Rdat")

data2 = cr.ls.dat %>%
  mutate(
    subid = as.integer(str_sub(subid, -4))
  ) %>%
  select(subid, memload,resptime,accuracy) %>%
  rename(rt = resptime, response = accuracy) %>%
  mutate(response = ifelse(response == "Correct", 1, 0)) %>%
  rename(id=subid)

data1 = data1 %>%
  filter(id %in% unique(data2$id)) %>%
  mutate(y = amnart_iq) %>%
  select(id, y, age, education)

data2 = 
  right_join(data2, data1 %>%select(id)) %>%
  select(id,memload,response,rt) %>%
  na.omit() %>%
  filter(rt > 0.1)



model = list(
  v ~ memload,
  y ~ age + education + v_0
)

fit = regddm(
  data1,
  data2,
  model,
  scale = FALSE,
  warmup = 500,
  iter = 1000
)

res = rstan::summary(fit)$summary %>% round(3)

min(data2$rt)

data2 %>%
  arrange(rt)

data2 %>%
  group_by(id) %>%
  summarise(n=n())
```



```{r}
library(gtsummary)
dat = read_csv("../test_data/CR_BL.csv") 
dat = dat %>%
  janitor::clean_names() %>%
  filter(subid>3999, age<40) %>%
  select(subid,age,gender,education,race,amnart_iq) %>%
  unique() %>%
  filter(subid %in% data1$subid)

ttt= data2 %>%
  group_by(id) %>%
  summarise(
    latency = mean(rt),
    accuracy = mean(response)
  ) %>%
  select(-id) %>%
  bind_cols(data1, .name_repair = "minimal")


data2 %>%
  group_by(id) %>%
  summarise(
    latency = mean(rt),
    accuracy = mean(response)
  ) %>%
  tbl_summary(
    statistic = list(all_continuous() ~ "{mean} ({sd})", all_categorical() ~ "{n} ({p}%)")
  )


dat %>%
  mutate(education = as.numeric(education)) %>%
  tbl_summary(
    type = list(education ~ "continuous"),
    statistic = list(all_continuous() ~ "{mean} ({sd})", all_categorical() ~ "{n} ({p}%)")
  )
```












